### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by gabyfulchic** [obaarne/Nagios2Slack#2]
Hi @obaarne,

I've followed your tuto, and i've well configured my centreon to send notifications to slack. I've got a good webhook incoming redirecting to my channel services.
But when i launch the script slack_host_notify.sh it writes : no such file or directory.

Good path and file (good rights too) : 
/usr/lib64/nagios/plugins/slack_host_notify.sh
: No such file or directory

It's not the same message when i miss the name see : 
/usr/lib64/nagios/plugins/slack_host_notif.sh
bash: /usr/lib64/nagios/plugins/slack_host_notif.sh: No such file or directory

Do you have any ideas ? I tried manually to send curl cmd and i well receive notif to slack.
![bug-slack](https://user-images.githubusercontent.com/22600727/44778909-64ca2b00-ab7e-11e8-82bb-207285100377.png)

Warmly FULCHIC Gaby

**Comment by obaarne** [comment]
Hi Gaby, 
Could it be the shebang line causing this ? 
Please try to change the first line in the scripts to :
#!/usr/env bash
or
#!/usr/bin/bash

**Comment by gabyfulchic** [comment]
Ty, i've found, i've downloaded your repo in a windows .zip. So there was compatibility error between the windows/linux. 
I've just had to use a cmd on the two scripts to escape a \r making the script fail.

Warmly FULCHIC Gaby

**Comment by obaarne** [comment]
Perfect, all good then. 
Cheers
