### ISSUE TITLE
invalid payload

### ISSUE THREAD

**Issue by TwoFaceSteph** [obaarne/Nagios2Slack#4]
Hi,

Some nagios service events has not been sent to Slack. After modify the slalc-service script to get an output to file I got this for all messages that couldn't be sent:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   456    0    15  100   441     42   1255 --:--:-- --:--:-- --:--:--  1256
invalid_payload

I guess that some ":" or some "/", "\" or other signs that need to be escaped are causing this issue.
Any thoughts about that ?

Here is the actual used service-slack -script:

```
##################################################################
#!/usr/bin/env bash

# Edit your Slack hook URL and footer icon URL
SLACK_URL=https://hooks.slack.com/services/[TOKEN]
FOOTER_ICON=/usr/local/nagios/share/images/logos/nagios.png

# Service Notification command example :

# define command {
#                command_name                          slack-service
#                command_line                          /usr/lib64/nagios/plugins/slack_service_notify "$NOTIFICATIONTYPE$"  "$HOSTNAME$" "$HOSTADDRESS$" "$SERVICEDESC$" "$SERVICESTATE$" "$SERVICEOUTPUT$" "$LONGDATETIME$" "$LASTHOSTSTATECHANGE$"
# }

case $5 in

"CRITICAL")
  MSG_COLOR="danger"
  ;;
"WARNING")
  MSG_COLOR="warning"
  ;;
"OK")
  MSG_COLOR="good"
  ;;
*)
  MSG_COLOR="#CCCCCC"
  ;;
esac

IFS='%'

SLACK_MSG="payload={\"attachments\":[{\"color\": \"$MSG_COLOR\",\"title\": \"Service $1 notification\",
\"text\": \"Host:        $2\\nIP:             $3\\nService:    $4\\nState:        $5\"},
{\"color\": \"$MSG_COLOR\",\"title\":\"Additional Info :\",\"text\":\"\\n$6\",
\"footer\": \"Nagios notification: $7\",\"footer_icon\": \"$FOOTER_ICON\"}]}"

#Send message to Slack
curl -4 -X POST --proxy internetproxy.boerse.dir:8004 --data "$SLACK_MSG" $SLACK_URL &>/usr/local/nagios/var/slack-service.log

unset IFS
#########################################################################

```
Thanks in advance

Stephan

**Comment by obaarne** [comment]
Hi Stephan ,

Yes, it's possible there something in the message is breaking the JSON string.
I'm not seeing the actual message passed from your log output, only the curl status.

Could you add a line to send $SLACK_MSG to the log file to try to capture it ?
`echo $SLACK_MSG >> usr/local/nagios/var/slack-service.log`

( I'm looking into using jq with a template instead for the JSON string, probably safer, but requires jq to be installed. )
