### ISSUE TITLE
Notifications are duplicated

### ISSUE THREAD

**Issue by Ido-Ozeri** [obaarne/Nagios2Slack#5]
Hello mate, 

First of all, thank you for creating this "plugin", it is extremely useful. 

I've followed your instructions **to the letter**, however I'm getting duplicate notifications in the same slack message body.

You can see the notification here:

https://imgur.com/a/dROAHX4

Do you have any idea as to why it happens? 
If need be, I'll paste my configuration here. 

Thanks in advance

**Comment by obaarne** [comment]
Hi there, 
I've not seen this on any deployment. 
Is there any chance you have more than 1 contact using the slack command perhaps ?
That is the only obvious explanation I can see...

**Comment by Ido-Ozeri** [comment]
> 

You're right on the money mate, that was a stupid overlook on my end!
I had a contactgroup with multiple contacts, hence the duplication. 

Thanks again!
